name: Run Postman Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Newman and htmlextra reporter
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra

    - name: Run Postman Collection
      run: |
        newman run REQRES.postman_collection.json \
          --environment ReqresChainUrl.postman_environment.json \
          --reporters cli,htmlextra \
          --reporter-htmlextra-export newman-report.html

    - name: Upload HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: postman-report
        path: newman-report.html

    - name: Send email notification
      if: success()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        secure: true
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Reqres Postman API Test Report"
        body: |
          Hello,

          The Reqres Postman API tests have completed successfully.

          The HTML report is attached.

          Regards,  
          GitHub Actions
        to: ${{ secrets.EMAIL_USERNAME }}
        from: ${{ secrets.EMAIL_USERNAME }}
        attachments: newman-report.html
